apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kj4hbsjxv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kj4hbsjxv-go 
  name: kj4hbsjxv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kj4hbsjxv-go 
